### ISSUE TITLE
Check size < maximum allowed size before uploading

### ISSUE THREAD

**Issue by imaginator** [richq/folders2flickr#48]
I have a failing upload for a 1.3GB file (maximum allowed video is 1GB)
```
2015-11-14 13:01:13,989 uploadr.py:532 -          uploadImage() Upload failed
Traceback (most recent call last):
  File "/home/simon/Documents/src/folders2flickr/f2flickr/uploadr.py", line 515, in uploadImage
    res = getResponse(url)
  File "/home/simon/Documents/src/folders2flickr/f2flickr/uploadr.py", line 102, in getResponse
    data = flickr.unmarshal(minidom.parse(urllib2.urlopen(url)))
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 32] Broken pipe>
```

**Comment by richq** [comment]
OK, good plan. As a work around you can use the `.f2fignore` feature to ignore this for now until I figure out a fix. i.e. `echo bigfile.avi > .f2fignore` and bigfile.avi won't be uploaded.

**Comment by imaginator** [comment]
Yep - got that working now to ignore the big ones.

Incidentally I notice that the memory balloons up on the big files. Does
the python script load the entire video into memory?

On 14 November 2015 at 17:47, Richard Quirk <notifications@github.com>
wrote:

> OK, good plan. As a work around you can use the .f2fignore feature to
> ignore this for now until I figure out a fix. i.e. echo bigfile.avi >
> .f2fignore and bigfile.avi won't be uploaded.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/richq/folders2flickr/issues/48#issuecomment-156718743>
> .
>



-- 
Simon Tennant | CEO Buddycloud <http://buddycloud.com> | +49 17 8545 0880 |
Meet <https://calendly.com/simon-tennant/buddycloud-call>
