### ISSUE TITLE
error in exifread.make_string(eval(printable))

### ISSUE THREAD

**Issue by gertjanvannoord** [richq/folders2flickr#57]
I get this error: 
2016-08-16 11:51:25,619 uploadr.py:532 -          uploadImage() Upload failed
Traceback (most recent call last):
  File "/home/vannoord/.local/lib/python2.7/site-packages/f2flickr/uploadr.py", line 494, in uploadImage
    exifstring = exifread.make_string(eval(printable))
  File "<string>", line 1
    [100, 0, 111, 0, 107, 0, 107, 0, 117, 0, 109, 0, 32, 0, 101, 0, 110, 0, 32, 0, ... ]

it does not tell me which photo is to blame (assuming there is a foto with buggy exif). 

I changed line 532 into
           logging.exception("Upload failed: %s",image)
to see which file causes problems

**Comment by richq** [comment]
Good plan, should be fixed in 0b735057dbf3c0ea132668af36d30ded52e7b6d9
